### ISSUE TITLE
Replace Yargs w/Cleye

### ISSUE THREAD

**Issue by timkendall** [timkendall/tql#103]
Cleye is a TypeScript native library https://github.com/privatenumber/cleye

**Comment by lorefnon** [comment]
Since this issue was opened, yargs has substantially improved their ts support and are also gradually moving their codebase to ts. In contrast this library hasn't gained much adoption. 

I recommend closing this in favor of migrating to latest version of Yargs, which is done in https://github.com/timkendall/tql/pull/116
