### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by maticzav** [timkendall/tql#30]
Hey! 👋🏿 

I couldn't find your email or Twitter link to reach out - sorry for opening an issue just for that.

I really like your project! I am working on something very, very similar ([Kayu](https://github.com/maticzav/kayu)) - do you think we could maybe merge the projects? I don't think it's beneficial to solve the same problem twice. I really like the idea of using TS to define queries and especially your approach to using them with urql and Apollo client (as"not writing alternative clients").

Well, let me know if you want to chat! I think we could learn a lot from each other. 😄

**Comment by timkendall** [comment]
Hey Matic, thanks for reaching out!

I like your project as well, very well written and marketed. Your approach (using implicit object returns as the DSL, having field selector functions pull values from a response) is actually the one I took when initially spiking out this library :) 

Ultimately I changed directions when TypeScript 4.1 came out with recursive conditional types because it enabled an even simpler DSL and library overall. Regardless I think there are merits to each approach so I'm curious to hear how you think we could merge the ideas.

Here are my goals for this project:
- **Provide the best API/DSL for interacting with a GraphQL API in TypeScript** - As we both have identified existing approaches are lacking in either ease-of-use (i.e write queries in GraphQL and then codegen specific functions/types every time) or type-safety (i.e write raw query strings). My team and I enjoyed the experience of [graphql-binding](https://github.com/dotansimha/graphql-binding) but it lacked a good API for defining arbitrary queries in code (i.e it acted as more of a REST API client by giving you all of the fields of a particular type which obv. negates a lot of the power of GraphQL) and is now deprecated. I think a library like mine or yours could pick up where they left off and finally provide true GraphQL API clients like we get with other types of APIs (REST, gRPC, etc.).
- **Be an operation writer and nothing more** - I want to keep this libraries' responsibility to just that of defining type-safe operations. Sticking to this single responsibility allows this library to work easily along-side existing full-fledged clients like Apollo, urql, etc. (note: I kind of started compromising on this slightly with the addition of my `Client` generation support and `Transport` concept)

Interested to hear your thoughts!

**Comment by maticzav** [comment]
Thank you for explaining your goals! I think we have a different set of goals for our projects - your list helped a lot! We could try merging the two, but it seems like we'd probably compromise on some of the features we want to bring to our libraries.

I still think it's a cool project though - I'll definitely look to it for inspiration. Thank you for taking the time to reply 😄

**Comment by timkendall** [comment]
Thanks again for reaching out. Will be using yours for inspiration too ;)
